
language: haskell
ghc:
  - "8.0.1"

sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.0.1

#--solver --resolver lts-7.2
#install:
#- stack --no-terminal --resolver lts-7.2 update

script:
  - pwd; ls; cd Autobahn; stack --no-terminal --skip-ghc-check test
#  - time stack --no-terminal test

