
sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=/opt/ghc/8.0.1/bin:$PATH

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.0.1

#--solver --resolver lts-7.2
install:
  - stack --no-terminal install cabal-install
  - stack --no-terminal init
  - stack --no-terminal setup
  - stack --no-terminal test --only-snapshot

script:
  - stack --no-terminal install
  - time stack --no-terminal test

